INSERT INTO [User] VALUES ('user1@gmail.com', '123456', 'Cao Dinh Sy Vy');
INSERT INTO [User] VALUES ('user2@gmail.com', '123456', 'Dinh Thi Thuy Linh');
INSERT INTO [User] VALUES ('user3@gmail.com', '123456', 'Cao Quy Nhan');
INSERT INTO [User] VALUES ('user4@gmail.com', '123456', 'User 4');


INSERT INTO [Restaurant] 
VALUES(null, 'Restaurant 1', 'This is restaurant 1', 5, 'pic_restaurant1', 
             '485 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 40),
      (null, 'Restaurant 2', 'This is restaurant 2', 4, 'pic_restaurant2', 
             '486 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 45),
      (null, 'Restaurant 3', 'This is restaurant 3', 3, 'pic_restaurant3', 
             '487 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 42),
      (null, 'Restaurant 4', 'This is restaurant 4', 4, 'pic_restaurant4', 
             '488 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 15),
      (null, 'Restaurant 5', 'This is restaurant 5', 5, 'pic_restaurant5', 
             '489 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 19),
      (null, 'Restaurant 6', 'This is restaurant 6', 4, 'pic_restaurant6', 
             '481 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 20),
      (null, 'Restaurant 7', 'This is restaurant 7', 3, 'pic_restaurant7', 
             '482 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 50),
      (null, 'Restaurant 8', 'This is restaurant 8', 4, 'pic_restaurant8', 
             '483 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 40),
      (null, 'Restaurant 9', 'This is restaurant 9', 5, 'pic_restaurant9', 
             '484 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 70),
      (null, 'Restaurant 10', 'This is restaurant 10', 4, 'pic_restaurant10', 
             '490 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 10),
      (null, 'Restaurant 11', 'This is restaurant 11', 3, 'pic_restaurant11', 
             '491 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 60),
      (null, 'Restaurant 12', 'This is restaurant 12', 4, 'pic_restaurant12', 
             '492 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 30);

INSERT INTO [Dish] VALUES
(null, 'Dish 1', 5,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 1),
(null, 'Dish 2', 6,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 200, 2),
(null, 'Dish 3', 8,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 40, 3),
(null, 'Dish 4', 2,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 700, 4),
(null, 'Dish 5', 9,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 5),
(null, 'Dish 6', 10,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 700, 6),
(null, 'Dish 7', 15,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 2, 400, 7),
(null, 'Dish 8', 6,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 200, 8),
(null, 'Dish 9', 7,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 600, 9),
(null, 'Dish 10', 9,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 400, 10),
(null, 'Dish 11', 1,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 500, 11),
(null, 'Dish 12', 5,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 100, 12),
(null, 'Dish 13', 3,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 500, 11),
(null, 'Dish 14', 7,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 80, 10),
(null, 'Dish 15', 2,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 300, 9),
(null, 'Dish 16', 8,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 700, 8),
(null, 'Dish 17', 9,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 200, 7),
(null, 'Dish 18', 5,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 800, 6),
(null, 'Dish 19', 4,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 200, 5),
(null, 'Dish 20', 6,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 300, 4),
(null, 'Dish 21', 5,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 700, 3),
(null, 'Dish 22', 8,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 500, 2),
(null, 'Dish 23', 12,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 600, 1),
(null, 'Dish 24', 20,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 200, 2),
(null, 'Dish 25', 3,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 3),
(null, 'Dish 26', 8,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 200, 4),
(null, 'Dish 27', 3,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 100, 5),
(null, 'Dish 28', 9,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 700, 6),
(null, 'Dish 29', 11,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 600, 7),
(null, 'Dish 30', 12,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 300, 8),
(null, 'Dish 31', 24,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 300, 9),
(null, 'Dish 32', 34,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 200, 10),
(null, 'Dish 33', 52,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 100, 11),
(null, 'Dish 34', 1,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 600, 12),
(null, 'Dish 35', 7,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 400, 11),
(null, 'Dish 36', 4,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 700, 10),
(null, 'Dish 37', 9,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 900, 9),
(null, 'Dish 38', 10,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 200, 8),
(null, 'Dish 39', 6,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 500, 7),
(null, 'Dish 40', 12,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 6);


