INSERT INTO [User] VALUES ('user1@gmail.com', '123456', 'Cao Dinh Sy Vy', 'pic_avatar1', 'Chợ Hiệp Bình Phước, Phường Hiệp Bình, TP. Thủ Đức');
INSERT INTO [User] VALUES ('user2@gmail.com', '123456', 'Dinh Thi Thuy Linh', 'pic_avatar2', '484 Lê Văn Việt, Phường Tăng Nhơn Phú A, TP. Thủ Đức');
INSERT INTO [User] VALUES ('user3@gmail.com', '123456', 'Cao Quy Nhan', 'pic_avatar3', '347 Lê Lợi, Quận 10, TP. Hồ Chí Minh');
INSERT INTO [User] VALUES ('user4@gmail.com', '123456', 'User 4', 'pic_avatar4', '15 Tô Ngọc Vân, TP. Thủ Đức');

INSERT INTO [Restaurant] 
VALUES(null, 'Lẩu Đức Trọc', 'This is restaurant', 5, 'pic_restaurant1',
             '485 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 40),
      (null, 'Linh Chi ', 'This is restaurant', 4, 'pic_restaurant2',
             '486 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 45),
      (null, 'Tiger Sugar Việt Nam ', 'This is restaurant 3', 3, 'pic_restaurant3',
             '487 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 42),
      (null, 'Xôi & Bánh Mì Pate Hải Phòng', 'This is restaurant 4', 4, 'pic_restaurant4',
             '488 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 15),
      (null, 'Gà Rán, Gà Luộc & Gà Muối Hoa Tiêu', 'This is restaurant 5', 5, 'pic_restaurant5',
             '489 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 19),
      (null, 'Sữa Chua Trân Châu Hạ Long Healthy', 'This is restaurant 6', 4, 'pic_restaurant6',
             '481 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 20),
      (null, 'Trà Sữa Tocotoco', 'This is restaurant 7', 3, 'pic_restaurant7',
             '482 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 50),
      (null, 'Hương Vị Việt - Gà Rán', 'This is restaurant 8', 4, 'pic_restaurant8',
             '483 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 40),
      (null, 'Bánh Giò Gia Hoàng - Hàng Bún', 'This is restaurant 9', 5, 'pic_restaurant9',
             '484 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 70),
      (null, 'Ngọc Ánh - Bún & Bánh Giò', 'This is restaurant 10', 4, 'pic_restaurant10',
             '490 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 10),
      (null, 'Tiger Sugar - Vũ Trọng Phụng', 'This is restaurant 11', 3, 'pic_restaurant11',
             '491 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 60),
      (null, 'Dimsum Điểm Tâm Đài Loan', 'This is restaurant 12', 4, 'pic_restaurant12',
             '492 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 30),
      (null, 'Deilyno', 'This is restaurant 12', 4, 'pic_restaurant1',
             '492 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 30),
      (null, 'Dồi Sụn Nướng & Ăn Vặt', 'This is restaurant 12', 4, 'pic_restaurant2',
             '492 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 30),
      (null, 'Teen Food - Các Món Ăn Vặt', 'This is restaurant 12', 4, 'pic_restaurant3',
                   '492 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 30),
      (null, 'A Lẩu - Cháo Lòng', 'This is restaurant 12', 4, 'pic_restaurant4',
                   '492 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 30),
      (null, 'Bún Đậu Mẹt Minh Thư', 'This is restaurant 12', 4, 'pic_restaurant5',
                   '492 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 30),
      (null, 'Dimsum Điểm Tâm Đài Loan', 'This is restaurant 12', 4, 'pic_restaurant6',
                   '492 Le Van Viet, Phuong Tang Nhon Phu A, TP Thu Duc', 30);


INSERT INTO [Dish] VALUES
(null, 'Dish 10', 5,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 1),
(null, 'Dish 9', 6,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 200, 2),
(null, 'Dish 8', 8,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 40, 3),
(null, 'Dish 7', 2,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 700, 4),
(null, 'Dish 6', 9,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 5),
(null, 'Dish 1', 10,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 700, 6),
(null, 'Dish 2', 15,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 2, 400, 7),
(null, 'Dish 3', 6,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 200, 8),
(null, 'Dish 4', 7,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 600, 9),
(null, 'Dish 5', 9,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 400, 10),
(null, 'Dish 20', 1,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 500, 11),
(null, 'Dish 19', 5,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 100, 12),
(null, 'Dish 18', 3,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 500, 11),
(null, 'Dish 17', 7,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 80, 10),
(null, 'Dish 16', 2,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 300, 9),
(null, 'Dish 15', 8,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 700, 8),
(null, 'Dish 14', 9,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 200, 7),
(null, 'Dish 13', 5,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 800, 6),
(null, 'Dish 12', 4,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 200, 5),
(null, 'Dish 11', 6,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 300, 4),
(null, 'Dish 21', 5,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 700, 3),
(null, 'Dish 22', 8,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 500, 2),
(null, 'Dish 23', 12,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 600, 1),
(null, 'Dish 24', 20,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 200, 2),
(null, 'Dish 25', 3,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 3),
(null, 'Dish 26', 8,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 200, 4),
(null, 'Dish 27', 3,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 100, 5),
(null, 'Dish 28', 9,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 700, 6),
(null, 'Dish 29', 11,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 600, 7),
(null, 'Dish 30', 12,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 300, 8),
(null, 'Dish 40', 24,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 300, 9),
(null, 'Dish 39', 34,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 200, 10),
(null, 'Dish 38', 52,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 100, 11),
(null, 'Dish 37', 1,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 600, 12),
(null, 'Dish 36', 7,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 3, 400, 11),
(null, 'Dish 35', 4,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 700, 10),
(null, 'Dish 34', 9,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 4, 900, 9),
(null, 'Dish 33', 10,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 200, 8),
(null, 'Dish 32', 6,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 500, 7),
(null, 'Dish 31', 12,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 600, 6),
(null, 'Dish 42', 13,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 700, 1),
(null, 'Dish 40', 14,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 800, 1),
(null, 'Dish 41', 15,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 900, 1),
(null, 'Dish 43', 16,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 1000, 1),
(null, 'Dish 44', 17,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 1),
(null, 'Dish 45', 12,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 400, 1),
(null, 'Dish 46', 13,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 500, 1),
(null, 'Dish 47', 14,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 600, 2),
(null, 'Dish 48', 15,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 2),
(null, 'Dish 49', 16,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 500, 2),
(null, 'Dish 50', 17,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 200, 2),
(null, 'Dish 60', 18,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 700, 2),
(null, 'Dish 59', 19,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 900, 3),
(null, 'Dish 58', 20,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 2000, 3),
(null, 'Dish 57', 13,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 360, 3),
(null, 'Dish 56', 14,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 500, 3),
(null, 'Dish 55', 15,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 800, 3),
(null, 'Dish 54', 16,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 900, 3),
(null, 'Dish 53', 13,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 1000, 4),
(null, 'Dish 52', 19,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 600, 4),
(null, 'Dish 51', 18,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 4),
(null, 'Dish 61', 17,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 4),
(null, 'Dish 62', 16,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 4),
(null, 'Dish 63', 15,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 5),
(null, 'Dish 64', 14,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 5),
(null, 'Dish 65', 13,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 5),
(null, 'Dish 66', 13,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 5),
(null, 'Dish 67', 12,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 5),
(null, 'Dish 68', 11,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 5),
(null, 'Dish 69', 10,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 6),
(null, 'Dish 70', 11,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 6),
(null, 'Dish 72', 13,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 6),
(null, 'Dish 74', 14,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 6),
(null, 'Dish 76', 15,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 6),
(null, 'Dish 78', 16,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 6),
(null, 'Dish 80', 17,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 6),
(null, 'Dish 71', 18,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 7),
(null, 'Dish 73', 19,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 7),
(null, 'Dish 75', 20,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 7),
(null, 'Dish 77', 12,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 7),
(null, 'Dish 79', 13,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 7),
(null, 'Dish 81', 14,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 7),
(null, 'Dish 82', 15,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 8),
(null, 'Dish 83', 16,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 8),
(null, 'Dish 84', 17,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 8),
(null, 'Dish 85', 18,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 8),
(null, 'Dish 86', 19,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 8),
(null, 'Dish 87', 15,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 8),
(null, 'Dish 88', 18,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 8),
(null, 'Dish 89', 13,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 9),
(null, 'Dish 90', 10,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 9),
(null, 'Dish 99', 16,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 9),
(null, 'Dish 98', 13,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 9),
(null, 'Dish 97', 17,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 9),
(null, 'Dish 96', 15,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 9),
(null, 'Dish 95', 13,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 9),
(null, 'Dish 94', 17,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 10),
(null, 'Dish 93', 12,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 10),
(null, 'Dish 92', 16,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 10),
(null, 'Dish 91', 19,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 10),
(null, 'Dish 100', 12,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 10),
(null, 'Dish 101', 13,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 10),
(null, 'Dish 102', 18,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 11),
(null, 'Dish 103', 11,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 11),
(null, 'Dish 104', 17,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 11),
(null, 'Dish 105', 18,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 11),
(null, 'Dish 106', 17,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 11),
(null, 'Dish 107', 13,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 11),
(null, 'Dish 108', 19,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 12),
(null, 'Dish 109', 11,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 12),
(null, 'Dish 110', 17,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 12),
(null, 'Dish 120', 15,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 12),
(null, 'Dish 119', 17,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 12),
(null, 'Dish 118', 18,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 12),
(null, 'Dish 117', 14,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 13),
(null, 'Dish 116', 18,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 13),
(null, 'Dish 115', 12,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 13),
(null, 'Dish 114', 15,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 13),
(null, 'Dish 113', 16,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 13),
(null, 'Dish 112', 12,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 13),
(null, 'Dish 111', 16,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 14),
(null, 'Dish 130', 13,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 14),
(null, 'Dish 129', 18,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 14),
(null, 'Dish 128', 19,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 14),
(null, 'Dish 127', 13,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 14),
(null, 'Dish 126', 16,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 14),
(null, 'Dish 125', 13,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 14),
(null, 'Dish 124', 18,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 14),
(null, 'Dish 123', 19,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 15),
(null, 'Dish 121', 11,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 15),
(null, 'Dish 130', 14,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 15),
(null, 'Dish 131', 15,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 15),
(null, 'Dish 132', 17,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 15),
(null, 'Dish 133', 18,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 15),
(null, 'Dish 134', 19,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 16),
(null, 'Dish 135', 10,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 16),
(null, 'Dish 136', 13,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 16),
(null, 'Dish 137', 15,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 16),
(null, 'Dish 138', 13,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 16),
(null, 'Dish 139', 17,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 16),
(null, 'Dish 140', 17,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 16),
(null, 'Dish 141', 12,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 17),
(null, 'Dish 142', 17,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 17),
(null, 'Dish 143', 17,'pic_dish2', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 17),
(null, 'Dish 144', 12,'pic_dish3', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 17),
(null, 'Dish 145', 15,'pic_dish4', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 17),
(null, 'Dish 146', 18,'pic_dish5', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 17),
(null, 'Dish 147', 15,'pic_dish6', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 18),
(null, 'Dish 148', 12,'pic_dish7', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 18),
(null, 'Dish 149', 16,'pic_dish8', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 18),
(null, 'Dish 160', 18,'pic_dish9', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 18),
(null, 'Dish 159', 14,'pic_dish10', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 18),
(null, 'Dish 158', 13,'pic_dish1', 'This is very delicious dish. This is very delicious dish. This is very delicious dish. ', 5, 300, 18);


